version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: jobseekr_laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel
    restart: always
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    container_name: node-api
    restart: always
    working_dir: /app
    volumes:
      - ./node-api:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: react
    restart: always
    working_dir: /app
    volumes:
      - ./react:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_LARAVEL_BASE_URL=http://localhost:8000/api
      - VITE_NODE_BASE_URL=http://localhost:5000/api
      - VITE_NODE_CHAT_URL=http://localhost:5000
    command: npm run dev -- --host

volumes:
  mysql_data:
  mongo_data:
